<a href="https://colab.research.google.com/github/Bhavya-Mistry/Data-Science/blob/main/p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_excel("p1.xlsx")
df.head()

       Airline Date_of_Journey    Source Destination  ... Duration Total_Stops Additional_Info  Price
0       IndiGo      24/03/2019  Banglore   New Delhi  ...   2h 50m    non-stop         No info   3897
1    Air India       1/05/2019   Kolkata    Banglore  ...   7h 25m     2 stops         No info   7662
2  Jet Airways       9/06/2019     Delhi      Cochin  ...      19h     2 stops         No info  13882
3       IndiGo      12/05/2019   Kolkata    Banglore  ...   5h 25m      1 stop         No info   6218
4       IndiGo      01/03/2019  Banglore   New Delhi  ...   4h 45m      1 stop         No info  13302

[5 rows x 11 columns]

In [ ]:
le = LabelEncoder()

In [ ]:
df["Airline"].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [ ]:
df["Airline_encoded"] = le.fit_transform(df["Airline"])
df.drop("Airline",axis=1, inplace=True)

In [ ]:
df["Source_encoded"] = le.fit_transform(df["Source"])
df.drop("Source", axis=1, inplace=True)

In [ ]:
df['Additional_Info_encoded'] = le.fit_transform(df["Additional_Info"])
df.drop("Additional_Info", inplace = True, axis=1)

In [ ]:
df["Destination_encoded"] = le.fit_transform(df["Destination"])
df.drop("Destination", axis = 1, inplace=True)

In [ ]:
df.isnull().sum()

Date_of_Journey            0
Route                      1
Dep_Time                   0
Arrival_Time               0
Duration                   0
Total_Stops                1
Price                      0
Airline_encoded            0
Source_encoded             0
Additional_Info_encoded    0
Destination_encoded        0
dtype: int64

In [ ]:
print(df["Total_Stops"].unique())

df.dropna(inplace=True)

df.isnull().sum()

['non-stop' '2 stops' '1 stop' '3 stops' nan '4 stops']

Date_of_Journey            0
Route                      0
Dep_Time                   0
Arrival_Time               0
Duration                   0
Total_Stops                0
Price                      0
Airline_encoded            0
Source_encoded             0
Additional_Info_encoded    0
Destination_encoded        0
dtype: int64

In [ ]:
df["Total_Stops"].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', '4 stops'],
      dtype=object)

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['non-stop', '2 stops', '1 stop', '3 stops', '4 stops']])

df["Total_Stops_encoded"] = oe.fit_transform(df[["Total_Stops"]])
df.drop("Total_Stops", axis=1, inplace=True)

In [ ]:
df.head()

  Date_of_Journey                  Route  ... Destination_encoded Total_Stops_encoded
0      24/03/2019              BLR → DEL  ...                   5                 0.0
1       1/05/2019  CCU → IXR → BBI → BLR  ...                   0                 1.0
2       9/06/2019  DEL → LKO → BOM → COK  ...                   1                 1.0
3      12/05/2019        CCU → NAG → BLR  ...                   0                 2.0
4      01/03/2019        BLR → NAG → DEL  ...                   5                 2.0

[5 rows x 11 columns]

In [ ]:
df["Date_of_Journey"].unique()

array(['24/03/2019', '1/05/2019', '9/06/2019', '12/05/2019', '01/03/2019',
       '24/06/2019', '12/03/2019', '27/05/2019', '1/06/2019',
       '18/04/2019', '9/05/2019', '24/04/2019', '3/03/2019', '15/04/2019',
       '12/06/2019', '6/03/2019', '21/03/2019', '3/04/2019', '6/05/2019',
       '15/05/2019', '18/06/2019', '15/06/2019', '6/04/2019',
       '18/05/2019', '27/06/2019', '21/05/2019', '06/03/2019',
       '3/06/2019', '15/03/2019', '3/05/2019', '9/03/2019', '6/06/2019',
       '24/05/2019', '09/03/2019', '1/04/2019', '21/04/2019',
       '21/06/2019', '27/03/2019', '18/03/2019', '12/04/2019',
       '9/04/2019', '1/03/2019', '03/03/2019', '27/04/2019'], dtype=object)

In [ ]:
df['Date_of_Journey'] = pd.to_datetime(df['Date_of_Journey'], format='%d/%m/%Y')

df.head()

df['Year'] = df['Date_of_Journey'].dt.year
df['Month'] = df['Date_of_Journey'].dt.month
df['Day'] = df['Date_of_Journey'].dt.day
df['DayOfWeek'] = df['Date_of_Journey'].dt.day_name()

df.drop("Date_of_Journey",axis=1,inplace=True)

df.head()

                   Route Dep_Time  Arrival_Time Duration  ...  Year  Month  Day  DayOfWeek
0              BLR → DEL    22:20  01:10 22 Mar   2h 50m  ...  2019      3   24     Sunday
1  CCU → IXR → BBI → BLR    05:50         13:15   7h 25m  ...  2019      5    1  Wednesday
2  DEL → LKO → BOM → COK    09:25  04:25 10 Jun      19h  ...  2019      6    9     Sunday
3        CCU → NAG → BLR    18:05         23:30   5h 25m  ...  2019      5   12     Sunday
4        BLR → NAG → DEL    16:50         21:35   4h 45m  ...  2019      3    1     Friday

[5 rows x 14 columns]

In [ ]:
df["Duration"].unique()

array(['2h 50m', '7h 25m', '19h', '5h 25m', '4h 45m', '2h 25m', '15h 30m',
       '21h 5m', '25h 30m', '7h 50m', '13h 15m', '2h 35m', '2h 15m',
       '12h 10m', '26h 35m', '4h 30m', '22h 35m', '23h', '20h 35m',
       '5h 10m', '15h 20m', '2h 55m', '13h 20m', '15h 10m', '5h 45m',
       '5h 55m', '13h 25m', '22h', '5h 30m', '10h 25m', '5h 15m',
       '2h 30m', '6h 15m', '11h 55m', '11h 5m', '8h 30m', '22h 5m',
       '2h 45m', '12h', '16h 5m', '19h 55m', '3h 15m', '25h 20m', '3h',
       '16h 15m', '15h 5m', '6h 30m', '25h 5m', '12h 25m', '27h 20m',
       '10h 15m', '10h 30m', '1h 30m', '1h 25m', '26h 30m', '7h 20m',
       '13h 30m', '5h', '19h 5m', '14h 50m', '2h 40m', '22h 10m',
       '9h 35m', '10h', '21h 20m', '18h 45m', '12h 20m', '18h', '9h 15m',
       '17h 30m', '16h 35m', '12h 15m', '7h 30m', '24h', '8h 55m',
       '7h 10m', '14h 30m', '30h 20m', '15h', '12h 45m', '10h 10m',
       '15h 25m', '14h 5m', '20h 15m', '23h 10m', '18h 10m', '16h',
       '2h 20m', '8h', '16h 55m', '3h 10m', '14h', '23h 50m', '21h 40m',
       '21h 15m', '10h 50m', '8h 15m', '8h 35m', '11h 50m', '27h 35m',
       '8h 25m', '20h 55m', '4h 50m', '8h 10m', '24h 25m', '23h 35m',
       '25h 45m', '26h 10m', '28h 50m', '25h 15m', '9h 20m', '9h 10m',
       '3h 5m', '11h 30m', '9h 30m', '17h 35m', '5h 5m', '25h 50m', '20h',
       '13h', '18h 25m', '24h 10m', '4h 55m', '25h 35m', '6h 20m',
       '18h 40m', '19h 25m', '29h 20m', '9h 5m', '10h 45m', '11h 40m',
       '22h 55m', '37h 25m', '25h 40m', '13h 55m', '8h 40m', '23h 30m',
       '12h 35m', '24h 15m', '1h 20m', '11h', '11h 15m', '14h 35m',
       '12h 55m', '9h', '7h 40m', '11h 45m', '24h 55m', '17h 5m',
       '29h 55m', '22h 15m', '14h 40m', '7h 15m', '20h 10m', '20h 45m',
       '27h', '24h 30m', '20h 25m', '5h 35m', '14h 45m', '5h 40m',
       '4h 5m', '15h 55m', '7h 45m', '28h 20m', '4h 20m', '3h 40m',
       '8h 50m', '23h 45m', '24h 45m', '21h 35m', '8h 5m', '6h 25m',
       '15h 50m', '26h 25m', '24h 50m', '26h', '23h 5m', '7h 55m',
       '26h 20m', '23h 15m', '5h 20m', '4h', '9h 45m', '8h 20m',
       '17h 25m', '7h 5m', '34h 5m', '6h 5m', '5h 50m', '7h', '4h 25m',
       '13h 45m', '19h 15m', '22h 30m', '16h 25m', '13h 50m', '27h 5m',
       '28h 10m', '4h 40m', '15h 40m', '4h 35m', '18h 30m', '38h 15m',
       '6h 35m', '12h 30m', '11h 20m', '7h 35m', '29h 35m', '26h 55m',
       '23h 40m', '12h 50m', '9h 50m', '21h 55m', '10h 55m', '21h 10m',
       '20h 40m', '30h', '13h 10m', '8h 45m', '6h 10m', '17h 45m',
       '21h 45m', '3h 55m', '17h 20m', '30h 30m', '21h 25m', '12h 40m',
       '24h 35m', '19h 10m', '22h 40m', '14h 55m', '21h', '6h 45m',
       '28h 40m', '9h 40m', '16h 40m', '16h 20m', '16h 45m', '1h 15m',
       '6h 55m', '11h 25m', '14h 20m', '12h 5m', '24h 5m', '28h 15m',
       '17h 50m', '20h 20m', '28h 5m', '10h 20m', '14h 15m', '35h 15m',
       '35h 35m', '26h 40m', '28h', '14h 25m', '13h 5m', '37h 20m',
       '36h 10m', '25h 55m', '35h 5m', '19h 45m', '27h 55m', '47h',
       '10h 35m', '1h 35m', '16h 10m', '38h 20m', '6h', '16h 50m',
       '14h 10m', '23h 20m', '17h 40m', '11h 35m', '18h 20m', '6h 40m',
       '30h 55m', '24h 40m', '29h 50m', '28h 25m', '17h 15m', '22h 45m',
       '25h 25m', '21h 50m', '33h 15m', '30h 15m', '3h 35m', '27h 40m',
       '30h 25m', '18h 50m', '27h 45m', '15h 15m', '10h 40m', '26h 15m',
       '36h 25m', '26h 50m', '15h 45m', '19h 40m', '22h 25m', '19h 35m',
       '25h', '26h 45m', '38h', '4h 15m', '25h 10m', '18h 15m', '6h 50m',
       '23h 55m', '17h 55m', '23h 25m', '17h 10m', '24h 20m', '28h 30m',
       '27h 10m', '19h 20m', '15h 35m', '9h 25m', '21h 30m', '34h 25m',
       '18h 35m', '29h 40m', '26h 5m', '29h 5m', '27h 25m', '16h 30m',
       '11h 10m', '28h 55m', '29h 10m', '34h', '30h 40m', '30h 45m',
       '32h 55m', '10h 5m', '35h 20m', '32h 5m', '31h 40m', '19h 50m',
       '33h 45m', '30h 10m', '13h 40m', '19h 30m', '31h 30m', '34h 30m',
       '27h 50m', '38h 35m', '42h 5m', '4h 10m', '39h 5m', '3h 50m', '5m',
       '32h 30m', '31h 55m', '33h 20m', '27h 30m', '18h 55m', '9h 55m',
       '41h 20m', '20h 5m', '31h 50m', '42h 45m', '3h 25m', '37h 10m',
       '29h 30m', '32h 20m', '20h 50m', '40h 20m', '13h 35m', '47h 40m'],
      dtype=object)