<a href="https://colab.research.google.com/github/Bhavya-Mistry/Data-Science/blob/main/ds_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
# 1) Read The dataset
df = pd.read_csv("cars_sampled.csv")

In [ ]:
# 2) Make a deep copy of the dataset
deep_copied_df = df.copy(deep=True)

In [ ]:
# 3) Get structure of the data and mention datatype of each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50001 entries, 0 to 50000
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dateCrawled          50001 non-null  object
 1   name                 50001 non-null  object
 2   seller               50001 non-null  object
 3   offerType            50001 non-null  object
 4   price                50001 non-null  int64
 5   abtest               50001 non-null  object
 6   vehicleType          44813 non-null  object
 7   yearOfRegistration   50001 non-null  int64
 8   gearbox              47177 non-null  object
 9   powerPS              50001 non-null  int64
 10  model                47243 non-null  object
 11  kilometer            50001 non-null  int64
 12  monthOfRegistration  50001 non-null  int64
 13  fuelType             45498 non-null  object
 14  brand                50001 non-null  object
 15  notRepairedDamage    40285 non-null  object
 16  dateCreated          50001 non-null  object
 17  postalCode           50001 non-null  int64
 18  lastSeen             50001 non-null  object
dtypes: int64(6), object(13)
memory usage: 7.2+ MB

In [ ]:
# 4) Get summary of the data
df.describe()

,price,yearOfRegistration,powerPS,kilometer,monthOfRegistration,postalCode
count,5.000100e+04,50001.000000,50001.000000,50001.000000,50001.000000,50001.000000
mean,6.559865e+03,2005.544229,116.496130,125613.687726,5.743725,50775.216696
std,8.581847e+04,122.991832,230.567709,40205.234483,3.711345,25743.701933
min,0.000000e+00,1000.000000,0.000000,5000.000000,0.000000,1067.000000
25%,1.150000e+03,1999.000000,69.000000,125000.000000,3.000000,30559.000000
50%,2.950000e+03,2003.000000,105.000000,150000.000000,6.000000,49504.000000
75%,7.190000e+03,2008.000000,150.000000,150000.000000,9.000000,71404.000000
max,1.234568e+07,9999.000000,19312.000000,150000.000000,12.000000,99998.000000

In [ ]:
# 5) Round all the decimal values till 3 places after decimal only
df = df.round(3)

In [ ]:
# 6) Display all the columns of this dataset
df.columns

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'kilometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'postalCode', 'lastSeen'],
      dtype='object')

In [ ]:
# 7) Drop unwanted columns [name, dateCrawled, dateCreated, PostalCode, lastSeen]
df.drop(columns=['name','dateCrawled','dateCreated','postalCode','lastSeen'], inplace=True)

In [ ]:
# 8) Remove duplicate records keep first occurrence of this
df = df.drop_duplicates()

In [ ]:
# 9) Sort YearofRegistration column based on index value
sorted_years = df["yearOfRegistration"].sort_index()

In [ ]:
# 10) Find the frequency of car based on price i.e. at the price of 1$ how many cars have been sold
price_frequency = df["price"].value_counts().sort_index()

In [ ]:
# 11) Find the frequency of car based on the PowerPS.
powerps_frequency = df["powerPS"].value_counts().sort_index()

In [ ]:
# 12) Make sure the working range of data should be
# a) YearOfRegistration < 2018 and YearOfRegistration>1950
# b) Price >= 100 and Price < =150000
# c) powerPS >=10 and PowerPS <= 500
filtered_df = df[
    (df["yearOfRegistration"] > 1950) & (df["yearOfRegistration"] < 2018) &
    (df["price"] >= 100) & (df["price"] <= 150000) &
    (df["powerPS"] >= 10) & (df["powerPS"] <= 500)
]
filtered_df.head() # Display first few rows of filtered data

,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,private,offer,4450,test,limousine,2003,manual,150,3er,150000,3,diesel,bmw,NaN
1,private,offer,13299,control,suv,2005,manual,163,xc_reihe,150000,6,diesel,volvo,no
2,private,offer,3200,test,bus,2003,manual,101,touran,150000,11,diesel,volkswagen,NaN
3,private,offer,4500,control,small car,2006,manual,86,ibiza,60000,12,petrol,seat,no
4,private,offer,18750,test,suv,2008,automatic,185,xc_reihe,150000,11,diesel,volvo,no

In [ ]:
# 13. Create new variable “Age” by adding YearOfRegistration and MonthOfRegistration considering 2018 is the current year.